import Header from './header'
import Footer from './footer'
import HomeHero from './home-hero'
import HomeCollection from './home-collection'
import Creators from './creators'
import Categories from './categories'
import Discover from './discover'
import MainWorks from './main-works'
import Digest from './digest'
import ArtistHero from './artist-hero'
import ArtistSecond from './artist-second'
import ArtistCards from './artist-cards'
import NftHero from './nft-hero'
import NftArtists from './nft-artists'
import MarketplaceHero from './marketplace-hero'
import Magic from './magic'
export {Header, Footer, HomeHero, HomeCollection, Creators,Categories,Discover,MainWorks,Digest,ArtistHero,ArtistSecond,ArtistCards,NftHero,NftArtists,MarketplaceHero,Magic }